### ISSUE TITLE
Area doctor

### ISSUE THREAD

**Issue by mariochaveztrujillo** [lexaguilar/AtencionClinica#1]
en el area doctor agregarles mas datos de llenar como código MINSA, especialidad, teléfono, dirección en donde el nombre la especialidad y el codigo minsa sean obligatorio

**Comment by mariochaveztrujillo** [comment]
En el área de subsidio cuando escojamos el diagnostico que tiene automáticamente me muestre el código del sie 10 a la par

**Comment by lexaguilar** [comment]
Favor adjuntar catalogo de cie10

**Comment by lexaguilar** [comment]
Corregido el CIE10
![image](https://user-images.githubusercontent.com/42163487/105118289-bd722980-5a93-11eb-9dde-75c87ff57b54.png)

**Comment by lexaguilar** [comment]
Corregido Doctores
![image](https://user-images.githubusercontent.com/42163487/105118350-da0e6180-5a93-11eb-9c54-23e7cd187258.png)
