### ISSUE TITLE
area de percapita

### ISSUE THREAD

**Issue by mariochaveztrujillo** [lexaguilar/AtencionClinica#2]
te adjunto la base de datos actual que envía el ins con los datos del asegurado y sus beneficiarios
[enero2021.xlsx](https://github.com/lexaguilar/AtencionClinica/files/5831832/enero2021.xlsx)

**Comment by mariochaveztrujillo** [comment]
te agrego la base de datos donde digitamos la hojas grandes que te enseñe ahi en las pestañas van el cie 10 y los reportes que necesitamos
[Base Ambulatorio ENERO 2021.xlsx](https://github.com/lexaguilar/AtencionClinica/files/5831836/Base.Ambulatorio.ENERO.2021.xlsx)

**Comment by mariochaveztrujillo** [comment]
otra observación entre al sistema con el usuario que me diste pero al cerrar la pagina y abrirla denuevo no me pidio usuario y contraseña

**Comment by lexaguilar** [comment]
Opcion de eliminar percapita
![image](https://user-images.githubusercontent.com/42163487/105130057-f0c0b280-5aab-11eb-8388-8c8f71a235e6.png)
![image](https://user-images.githubusercontent.com/42163487/105130066-f6b69380-5aab-11eb-9b93-b55e92d8ee96.png)

**Comment by mariochaveztrujillo** [comment]
una pregunta pq esta la opción de eliminar percapita al eliminar eso no se eliminan todas los movimientos que los paciente han tenido en el mes

**Comment by lexaguilar** [comment]
Porque no podes afectar lo movimientos, esto incluye, admision, transferencias, recetas, examenes de laboratorio, farmacia, mrp, si eliminas un percapital el sistema quedara conforme al percapita anterior, si hay pacientes que ya pasaron admision y consultar, esos registros quedaran grabados, asi que debes de tener mucho cuidado en la administracion del percapita
