### ISSUE TITLE
AREA de facturacion

### ISSUE THREAD

**Issue by mariochaveztrujillo** [lexaguilar/AtencionClinica#3]
![no carga procedimiento](https://user-images.githubusercontent.com/77633958/105729873-47d2e700-5ef3-11eb-996f-bab61ffabb46.jpg)
Buenos dias en el area de facturacion no carga los procedimiento motivo por el cual no puedo terminar la factura ademas ahi dice are no procedimiento

**Comment by mariochaveztrujillo** [comment]
en el area de cita cuando agrego un medico
![horario](https://user-images.githubusercontent.com/77633958/105731492-165b1b00-5ef5-11eb-9105-b217396dcc78.jpg)

**Comment by lexaguilar** [comment]
Cuando se cree un procedimiento, se debe de agregar a que area pertenece ese procedimiento
![image](https://user-images.githubusercontent.com/42163487/105782786-bab38080-5f3a-11eb-90ec-4c8d1e072876.png)
Esto es con el fin de que los procedimiento solo cargue por area, es decir cada area tendra sus propios procedimientos

**Comment by lexaguilar** [comment]
Para los horarios de los doctores, debes entrar a la opcion doctores
![image](https://user-images.githubusercontent.com/42163487/105782984-0f56fb80-5f3b-11eb-8ba3-7d57268c54b5.png)

Aca seleccionar el doctor
e ingresas el horario
![image](https://user-images.githubusercontent.com/42163487/105783225-9c9a5000-5f3b-11eb-9b7f-8c79c6b913bd.png)
El horario esta parametrizado
Debes seleccionar el doctor, a que hora inicia, cuanto pacientes atiende y el tiempo que demora en atender un paciente
En la parte de horario, debes usar la formula siguiente:
[1,2,3,4].includes({dayOfWeek}), donde el 1,2,3 y 4, son los dias de la semana, y  dayOfWeek es la varia que toma el sistema
usa esta formula para indicar que dias va trabajar el doctor, en este ejemplo se pone 1,2,3,4 indicando que los dias que trabaja son lunes, martes, miercoles y jueves, puedes modificar los valores para dar diferentes dias de semana

**Comment by lexaguilar** [comment]
Esta formnula **[5].includes({dayOfWeek})** indica que el doctor solo trabajara los 5 osea los viernes de cada semana
Usa esta otra formula para decir que solo trabajara los dos ultmos dias de cada vez **[5].includes({dayOfWeek}) && {day} > 18**, estas indicando que va trabajar los vienres  (dia 5 de la semana) de las dos ultimas semanas de mes, puedes hacer lo mismo para lo que trabajan las primeras semanas del mes
