### ISSUE TITLE
Admision de puesto medico

### ISSUE THREAD

**Issue by mariochaveztrujillo** [lexaguilar/AtencionClinica#49]
En la admisión del puesto medico que cargue por defecto Medicina general ya que en los puestos no hay especialidades

**Comment by lexaguilar** [comment]
![Admision de puesto medico #49](https://user-images.githubusercontent.com/42163487/122092578-51d48400-cdc7-11eb-8da4-1dd1804f6b9a.gif)

**Comment by mariochaveztrujillo** [comment]
---------- Forwarded message ---------
De: ***@***.*** ***@***.***>
Date: mié, 16 jun 2021 a las 15:42
Subject: RE: Distribución de análisis deacuerdo a cada área del Laboratorio.
To: Sound Music Chanel ***@***.***>


Buenas tardes Ing. le envío estándares por prueba.
------------------------------
*De:* Sound Music Chanel ***@***.***>
*Enviado:* miércoles, 9 de junio de 2021 22:05
*Para:* ***@***.*** ***@***.***>
*Asunto:* Re: Distribución de análisis deacuerdo a cada área del
Laboratorio.

Gracias Gabriel acordate de estándares de los exámenes

El mié, 9 jun 2021 a las 12:26, ***@***.*** (<
***@***.***>) escribió:



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
