### ISSUE TITLE
Problema en factura

### ISSUE THREAD

**Issue by mariochaveztrujillo** [lexaguilar/AtencionClinica#50]
al crear factura de privado hemodialisis le agrege  un procedimiento mas como es colocacion de cateter que vale 450 mas 140 que vale la secion de hemodialisis y en la facturacion agrega 2 veces la secion de privado pero no agrega la colocacion de cateter
![image](https://user-images.githubusercontent.com/77633958/121600754-31d94500-ca02-11eb-828f-9586c0358e3c.png)

**Comment by lexaguilar** [comment]
Corregido
