### ISSUE TITLE
CAMBIO EN ADMISION

### ISSUE THREAD

**Issue by mariochaveztrujillo** [lexaguilar/AtencionClinica#51]
- [x]  - 1. Agregar en la búsqueda de paciente ponga ademas de si esta activo ponga la empresa y el numero de inss del asegurado
- [x]  - 2. en la busqueda se pueda buscar al asegurado con el numero de inss de beneficiario ya sea conyugue e hijo
- [x]  - 3. poder ver los beneficiarios que hemos agregados y poder exportarlo y saber cuantos beneficiarios conyuges e hijos tiene la empresa
- [x]  - 4. corregir el tiempo de sesión ya que dura poco
- [x]  - 5. corregir el error inesperado que te envié en la foto

**Comment by lexaguilar** [comment]
![image](https://user-images.githubusercontent.com/42163487/124364474-0a3f5c00-dbff-11eb-9536-45e5f45a73b9.png)

Esta mala la fecha de nacimiento del cliente

**Comment by mariochaveztrujillo** [comment]
Te envio la base de datos del mes de Julio 2021 completa como la manda el
INSS

**Comment by lexaguilar** [comment]
Listo
