### ISSUE TITLE
CAMBIOS EN LOS FILTROS DEL PERCAPITA Y ASEGURADO

### ISSUE THREAD

**Issue by mariochaveztrujillo** [lexaguilar/AtencionClinica#52]
1. en esta área los filtros de búsquedas por nombre, apellido y fecha no funcionan solo por numero de INS
2. en el área de asegurado no carga el numero patronal e igual los filtros no funcionan

**Comment by lexaguilar** [comment]
Se atienden en el [isuue#67](https://github.com/lexaguilar/AtencionClinica/issues/67) y  [isuue#68](https://github.com/lexaguilar/AtencionClinica/issues/68)
