### ISSUE TITLE
Realizar cambios

### ISSUE THREAD

**Issue by mariochaveztrujillo** [lexaguilar/AtencionClinica#55]
- [x]  En la pestaña servicio admisiones del dia de hoy quiero darle una nueva orden y se pone en blanco
- [x]  En admisiones del dia de hoy el filtro de inss solamente filtra hasta que pones todo el numero
- [x]  esto que se pone en blanco cuando ponesmos nueva orden solo pasa con el usuario de farmacia 
![image](https://user-images.githubusercontent.com/77633958/124676083-0ddf1700-de7b-11eb-95fe-a932f8aef571.png)

**Comment by lexaguilar** [comment]
Listo
