### ISSUE TITLE
Factura rapida

### ISSUE THREAD

**Issue by lexaguilar** [lexaguilar/AtencionClinica#59]
- [x] Factura rapida que aparezca Farmacia Privada
- [x] En caja no funcionan los filtro (Por nombre)

**Comment by alpha16180** [comment]
Farmacia Privada:
![image](https://user-images.githubusercontent.com/47343189/131773568-12c1cd39-6719-45f0-9342-c46e15ed9a70.png)

Filtro por Nombre:
![image](https://user-images.githubusercontent.com/47343189/131773765-d3985c09-4659-4267-baaa-bc79c8f06be9.png)
