### ISSUE TITLE
Hemodialisis

### ISSUE THREAD

**Issue by lexaguilar** [lexaguilar/AtencionClinica#60]
En caja poner el doctor al momento de admisionar para Hemo

Agregar en caja->nuevo combo de doctores y modificar el controlador Bill(POST) i enviar el doctorID

**Comment by alpha16180** [comment]
Frontend:
![image](https://user-images.githubusercontent.com/47343189/132133944-ad06d34c-a31d-43b6-a1c6-f61739f35bee.png)

Backend:
![image](https://user-images.githubusercontent.com/47343189/132133994-c0b31565-012d-4e63-b752-f5b03c01cd93.png)

bd:
![image](https://user-images.githubusercontent.com/47343189/132134012-4b352dab-ed15-45dd-90f0-9373506f47a4.png)
