### ISSUE TITLE
Mostrar la fecha que ingreso el beneficiario #41

### ISSUE THREAD

**Issue by lexaguilar** [lexaguilar/AtencionClinica#65]
Que desde la pantalla de beneficiarios Ficheros -> Beneficiarios por asegurado
![image](https://user-images.githubusercontent.com/42163487/132138623-eb9ff520-3155-4bb8-bc2d-fe537c36de65.png)
se puede ver en una columna la fecha cuando el beneficiario se creo

![image](https://user-images.githubusercontent.com/42163487/132138659-e3fd2a48-cd23-403d-b9d1-ba4215763e0c.png)

La columna ya existe en la tabla de Beneficiaries, solo es mostrarla

Revisar la opcion de editar, ya que este campo no es modificable, validar que no se pueda modificar desde la opción de editar
![image](https://user-images.githubusercontent.com/42163487/132138761-d7979eb8-0c0f-4ab3-bd0a-7dfc36133b99.png)

Quitar el campo Inss alternativo y mostrar la fecha de creacion (CreateAt) pero que solo este campo no se pueda editar
![image](https://user-images.githubusercontent.com/42163487/132616631-ff87cc1a-ac81-4500-b710-dc726b667c61.png)

**Comment by alpha16180** [comment]
Fecha creacion:
![image](https://user-images.githubusercontent.com/47343189/132938131-7a589a64-b7a9-48e4-b060-3b343fe2df8a.png)

edicion:
![image](https://user-images.githubusercontent.com/47343189/132938182-04cb2f96-6216-41a7-84e7-f0ee967c3262.png)
