### ISSUE TITLE
Corregir filtros en percapita

### ISSUE THREAD

**Issue by lexaguilar** [lexaguilar/AtencionClinica#67]
En la opción de Ficheros -> Percapita 
No filtra el grid por nombre o apellido y Patronal Id.
![image](https://user-images.githubusercontent.com/42163487/132140095-289ed96a-7b1f-4e9e-bf9c-36d7fde26bef.png)

**Comment by alpha16180** [comment]
![image](https://user-images.githubusercontent.com/47343189/132937523-a7c96f87-2eb9-4d1a-a67b-9fee1dac3727.png)
