### ISSUE TITLE
Numero patronal

### ISSUE THREAD

**Issue by lexaguilar** [lexaguilar/AtencionClinica#68]
En la opción  Ficheros -> Asegurados
Mostrar el numero Patronal
![image](https://user-images.githubusercontent.com/42163487/132614940-e3c8d1b5-8d93-4c0f-9874-8c0b254fee08.png)

Los valores ya estan en la tabla Customers, revisar porque no los muestra

**Comment by alpha16180** [comment]
Correcion realizada:
![image](https://user-images.githubusercontent.com/47343189/132937308-1de9f51e-d9f2-4984-965f-6b28a03e8931.png)
