### ISSUE TITLE
Compras

### ISSUE THREAD

**Issue by lexaguilar** [lexaguilar/AtencionClinica#76]
- [x] El campo observación no debe ser requerido
- [x] La columna total, debe calcularse en base solo a la cantidad (omitir las regalias)
- [x] Agregar el total de la factura a pagar (en el footer)
https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/GridSummaries/React/Light/

![image](https://user-images.githubusercontent.com/42163487/135383977-f9d3efcf-43e3-43db-8033-29d354350b8f.png)

**Comment by alpha16180** [comment]
![image](https://user-images.githubusercontent.com/47343189/136309643-fb4cc9b0-979a-4e6c-a3c0-6d4f6157b927.png)
