### ISSUE TITLE
Editar compra

### ISSUE THREAD

**Issue by lexaguilar** [lexaguilar/AtencionClinica#77]
- [x] Si al editar una compra, yo modifico un valor cualquiera, el botón de procesar de debe de deshabilitar, para que el usuario presione guardar y luego si poder procesar, ya que puede confundir cambiar un valor y luego darle en procesar, el sistema procesara con los datos anterior y no con los nuevos.

- [ ] Si si esta editando un compra, que al momento de guardar, no se cierre la ventana

![image](https://user-images.githubusercontent.com/42163487/135384309-d2a494a6-93be-47c3-ab79-ef30ec7dc9ea.png)

**Comment by alpha16180** [comment]
![image](https://user-images.githubusercontent.com/47343189/136280453-862a22aa-7de5-4dac-87b5-2e0a0d7ed1a0.png)
